name: Update

on:
  workflow_dispatch: # manual run
  push:
    branches:
      - master
  schedule:
    # Run at midnight on Sunday (UTC)
    - cron: "0 0 * * 0"

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Update fonts
        run: ./update.sh

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
